import type { FieldMapping } from '../fillPdf';

export const va221990tMapping: FieldMapping = {
  // Applicant
  firstName: { pdfFieldName: 'form1[0].#subform[0].firstname1[0]', type: 'text' },
  middleInitial: { pdfFieldName: 'form1[0].#subform[0].mi1[0]', type: 'text' },
  lastName: { pdfFieldName: 'form1[0].#subform[0].lastname1[0]', type: 'text' },
  ssn_1: { pdfFieldName: 'form1[0].#subform[0].#area[1].ssna1[0]', type: 'text' },
  ssn_2: { pdfFieldName: 'form1[0].#subform[0].#area[1].ssna2[0]', type: 'text' },
  ssn_3: { pdfFieldName: 'form1[0].#subform[0].#area[1].ssna3[0]', type: 'text' },
  dob_month: { pdfFieldName: 'form1[0].#subform[0].#area[0].dateofbirth1[0]', type: 'text' },
  dob_day: { pdfFieldName: 'form1[0].#subform[0].#area[0].dateofbirth2[0]', type: 'text' },
  dob_year: { pdfFieldName: 'form1[0].#subform[0].#area[0].dateofbirth3[0]', type: 'text' },
  sex_male: { pdfFieldName: 'form1[0].#subform[0].MALE[0]', type: 'checkbox' },
  sex_female: { pdfFieldName: 'form1[0].#subform[0].FEMALE[0]', type: 'checkbox' },
  vaFileNumber: { pdfFieldName: 'form1[0].#subform[0].filenumber[0]', type: 'text' },
  address: { pdfFieldName: 'form1[0].#subform[0].mailingaddress[0]', type: 'text' },
  apartment: { pdfFieldName: 'form1[0].#subform[0].apartment[0]', type: 'text' },
  cityStateZip: { pdfFieldName: 'form1[0].#subform[0].numberandstreet[0]', type: 'text' },
  zip4: { pdfFieldName: 'form1[0].#subform[0].zip4[0]', type: 'text' },
  stateCode: { pdfFieldName: 'form1[0].#subform[0].state[0]', type: 'text' },
  zip5: { pdfFieldName: 'form1[0].#subform[0].zip5[0]', type: 'text' },
  payee: { pdfFieldName: 'form1[0].#subform[0].payee[0]', type: 'text' },

  // Course Info
  courseName: { pdfFieldName: 'form1[0].#subform[0].COURSENAME[0]', type: 'text' },
  creditHours: { pdfFieldName: 'form1[0].#subform[0].CREDIT8[0]', type: 'text' },
  finalGrade: { pdfFieldName: 'form1[0].#subform[0].FINAL9[0]', type: 'text' },
  unitCost: { pdfFieldName: 'form1[0].#subform[0].UNIT10[0]', type: 'text' },
  tutorName: { pdfFieldName: 'form1[0].#subform[0].NAME11[0]', type: 'text' },

  // Sessions
  session1Month: { pdfFieldName: 'form1[0].#subform[0].MONTHANDYEAR1[0]', type: 'text' },
  session1Dates: { pdfFieldName: 'form1[0].#subform[0].EXACTDATES1[0]', type: 'text' },
  session1Hours: { pdfFieldName: 'form1[0].#subform[0].HOURSNO1[0]', type: 'text' },
  session1Charge: { pdfFieldName: 'form1[0].#subform[0].CHARGE1[0]', type: 'text' },
  session1Total: { pdfFieldName: 'form1[0].#subform[0].TOTALCHARGES1[0]', type: 'text' },
  session2Month: { pdfFieldName: 'form1[0].#subform[0].MONTHANDYEAR2[0]', type: 'text' },
  session2Dates: { pdfFieldName: 'form1[0].#subform[0].EXACTDATES2[0]', type: 'text' },
  session2Hours: { pdfFieldName: 'form1[0].#subform[0].HOURSNO2[0]', type: 'text' },
  session2Charge: { pdfFieldName: 'form1[0].#subform[0].CHARGE2[0]', type: 'text' },
  session2Total: { pdfFieldName: 'form1[0].#subform[0].TOTALCHARGES2[0]', type: 'text' },
  session3Month: { pdfFieldName: 'form1[0].#subform[0].MONTHANDYEAR3[0]', type: 'text' },
  session3Dates: { pdfFieldName: 'form1[0].#subform[0].EXACTDATES3[0]', type: 'text' },
  session3Hours: { pdfFieldName: 'form1[0].#subform[0].HOURSNO3[0]', type: 'text' },
  session3Charge: { pdfFieldName: 'form1[0].#subform[0].CHARGE3[0]', type: 'text' },
  session3Total: { pdfFieldName: 'form1[0].#subform[0].TOTALCHARGES3[0]', type: 'text' },
  session4Month: { pdfFieldName: 'form1[0].#subform[0].MONTHANDYEAR4[0]', type: 'text' },
  session4Dates: { pdfFieldName: 'form1[0].#subform[0].EXACTDATES4[0]', type: 'text' },
  session4Hours: { pdfFieldName: 'form1[0].#subform[0].HOURSNO4[0]', type: 'text' },
  session4Charge: { pdfFieldName: 'form1[0].#subform[0].CHARGE4[0]', type: 'text' },
  session4Total: { pdfFieldName: 'form1[0].#subform[0].TOTALCHARGES4[0]', type: 'text' },
  session5Month: { pdfFieldName: 'form1[0].#subform[0].MONTHANDYEAR5[0]', type: 'text' },
  session5Dates: { pdfFieldName: 'form1[0].#subform[0].EXACTDATES5[0]', type: 'text' },
  session5Hours: { pdfFieldName: 'form1[0].#subform[0].HOURSNO5[0]', type: 'text' },
  session5Charge: { pdfFieldName: 'form1[0].#subform[0].CHARGE5[0]', type: 'text' },
  session5Total: { pdfFieldName: 'form1[0].#subform[0].TOTALCHARGES5[0]', type: 'text' },
  session6Month: { pdfFieldName: 'form1[0].#subform[0].MONTHANDYEAR6[0]', type: 'text' },
  session6Dates: { pdfFieldName: 'form1[0].#subform[0].EXACTDATES6[0]', type: 'text' },
  session6Hours: { pdfFieldName: 'form1[0].#subform[0].HOURSNO6[0]', type: 'text' },
  session6Charge: { pdfFieldName: 'form1[0].#subform[0].CHARGE6[0]', type: 'text' },
  session6Total: { pdfFieldName: 'form1[0].#subform[0].TOTALCHARGES6[0]', type: 'text' },

  totalPayment: { pdfFieldName: 'form1[0].#subform[0].F\\.TOTALPAYMENTDUE[0]', type: 'text' },

  // School Certification
  schoolNameAddress: { pdfFieldName: 'form1[0].#subform[0].NAMEADDRESS15[0]', type: 'text' },
  studentEmail: { pdfFieldName: 'form1[0].#subform[0].EMAIL13c[0]', type: 'text' },
};
